version: "3.8"

services:
  alert-api:
    build: .
    container_name: alert-api
    expose:
      - "5000" # exposed to Docker network, not the host
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alert-api.rule=Host(`alert-api.ryan-jasinski.com`)"
      - "traefik.http.routers.alert-api.entrypoints=websecure"
      - "traefik.http.routers.alert-api.tls=true"
      - "traefik.http.routers.alert-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.alert-api.loadbalancer.server.port=5000"
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    external: true
