version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    volumes:
      - .:/app # Mount current directory for live reload
    ports:
      - "5000:5000" # Expose port to host for local dev
    networks:
      - web

networks:
  web:
    external: true
