services:
  web:
    build: .
    container_name: alert-api
    expose:
      - "5000" # Only exposed inside Docker network
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alert-api-secret.rule=Host(`ryan-jasinski.com`) && PathPrefix(`/secret`)"
      - "traefik.http.routers.alert-api-secret.entrypoints=websecure"
      - "traefik.http.routers.alert-api-secret.tls=true"
      - "traefik.http.routers.alert-api-secret.tls.certresolver=letsencrypt"
      - "traefik.http.routers.alert-api-secret.middlewares=strip-secret-prefix@file"
      - "traefik.http.services.alert-api-service.loadbalancer.server.port=5000"
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    external: true
